name: C/C++ CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  BUILD_DIR: build

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup CMake
        uses: jwlawson/actions-setup-cmake@v1
        with:
          version: '3.23'

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Configure CMake
        run: cmake -S . -B ${{ env.BUILD_DIR }}

      - name: Build targets
        run: |
          cmake --build build --target test_exec -- -j$(nproc)
          cmake --build build --target run -- -j$(nproc)

      - name: Run unit tests
        run: |
          cd ${{ env.BUILD_DIR }}
          ctest --output-on-failure

      - name: Run 'run' — case 1
        run: |
          # Предполагается, что в repo есть test/ci/input1.txt и test/ci/expected1.txt
          ./${{ env.BUILD_DIR }}/run < .github-tests/input1.txt > out1.txt
          diff -u .github-tests/expected1.txt out1.txt
          
