name: Testing
on:
  push:
    branches:
      - main
  pull_request:
env:
  BUILD_DIR: cmake-build
  TEST_DIR: .github-tests/tests
  SCRIPT_DIR: .github-tests/srcipts
jobs:
  Content:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: work tree
        run: |
          chmod +x ./${{ env.SCRIPT_DIR }}/work_tree.sh
          ./${{ env.SCRIPT_DIR }}/work_tree.sh ./
      - name: content
        run: |
          chmod +x ./${{ env.SCRIPT_DIR }}/content.sh
          ./${{ env.SCRIPT_DIR }}/content.sh
  Build:
    needs: Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          cmod +x ./${{ env.SCRIPT_DIR }}/build.sh
          ./${{ env.SCRIPT_DIR }}/build.sh ${{ env.BUILD_DIR }}
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.BUILD_DIR }}
          overwrite: true
  Gtest:
    needs: Content
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: load artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ env.BUILD_DIR }}
      - name: run gtest
        run: |
          cd ${{ env.BUILD_DIR }}
          ctest --output-on-failure
  Main-logic:
    needs: Gtest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_num: [ 1, 2 ]
    steps:
      - uses: actions/checkout@v4
      - name: load artifact
        uses: actions/download-artifact@v4
        with:
          name: build
          path: ${{ env.BUILD_DIR }}
      - name: run
        run: |
          chmod +x ./${{ env.SCRIPT_DIR }}/run.sh
          /${{ env.SCRIPT_DIR }}/run.sh ${{ env.BUILD_DIR }} ${{ env.TESTS_DIR }} ${{ matrix.test_num }}
